version: "1.0"
services:
  app:
    image: openjdk:21
    container_name: sistema_produtos
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:8080"
    volumes:
      - "./target/sistema_produtos-0.0.1-SNAPSHOT.jar:/app/sistema_produtos.jar"
    command: ["java", "-jar"]