spring:
    application: 
        name: sistema_produtos

    datasource:
        url: jdbc:sqlite:database.sqlite
        driver-class-name: org.sqlite.JDBC

    jpa:
        database-platform: com.igor_nascimento.sistema_produtos.config.SQLiteDialect
        hibernate:
            ddl-auto: update
        show-sql: true

server:
    servlet:
        context-path: /${spring.application.name}
    port: 8080
    ssl:
        enabled: false
